#!/bin/bash
# OMPSS Startup Service script v1.0 by Nerijus Barauskas
# USAGE: start|stop|status|logs
#
case "$1" in
start)
echo "Starting OMPSS..."
sudo /etc/ompss/ompss.sh start
;;
stop)
echo "Stopping OMPSS..."
sudo /etc/ompss/ompss.sh stop
;;
restart)
echo "Stopping OMPSS..."
sudo /etc/ompss/ompss.sh stop
echo "Starting OMPSS..."
sudo /etc/ompss/ompss.sh start
;;
logs)
echo "OMPSS Logs."
echo "Not implemented yet"
#sudo /etc/ompss/ompss.sh log
;;
status)
# Check to see if the process is running
echo "OMPSS Status"
sudo /etc/ompss/ompss.sh status
;;
 
*)
echo "OMPSS Service"
echo $"Usage: $0 {start|stop|status|logs}"
exit 1
esac
exit 0
