#!/bin/bash
# LifeRay Startup Service script v1.0 by Faraz Haider 6 May 2012
# acts as startup service script for LifeRay Portal.
# USAGE: start|stop|status|logs
#
case "$1" in
start)
echo "Starting OMPSS..."
sudo /etc/ompss/ompss.sh start
;;
stop)
echo "Stopping OMPSS..."
sudo /etc/ompss/ompss.sh stop
;;
restart)
echo "Stopping OMPSS..."
sudo /etc/ompss/ompss.sh stop
echo "Starting OMPSS..."
sudo /etc/ompss/ompss.sh start
;;
logs)
echo "OMPSS Logs."
sudo /etc/ompss/ompss.sh log
;;
status)
# Check to see if the process is running
echo "OMPSS Status"
sudo /etc/ompss/ompss.sh status
;;
 
*)
echo "LifeRay Web Portal Service"
echo $"Usage: $0 {start|stop|status|logs}"
exit 1
esac
exit 0
